feature_1 = Feature.create(name: "Automation")
feature_2 = Feature.create(name: "Integration")
feature_3 = Feature.create(name: "Speed")

test_1 = Test.create(name: "Test 1")
test_2 = Test.create(name: "Test 2", status: "passed")
test_3 = Test.create(name: "Test 3", status: "failed")
test_4 = Test.create(name: "Test 4")
test_5 = Test.create(name: "Test 5", status: "passed")
test_6 = Test.create(name: "Test 6", status: "failed")
test_7 = Test.create(name: "Test 7")
test_8 = Test.create(name: "Test 8", status: "passed")
test_9 = Test.create(name: "Test 9", status: "failed")
